### ISSUE TITLE
The Privacy Shield Embed is broken.

### ISSUE THREAD

**Issue by HACKER-3000** [tosdr/CrispCMS#123]
## Description
At the bottom of a services page there is  the privacy shield embed wich looks like this:
```html
<a href="/en/service/3892">
    <img src="https://shields.tosdr.org/en_3892.svg"/>
</a>
```
but shouldnt it look more like this?
```html
<a href="https://tosdr.org/en/service/3892">
    <img src="https://shields.tosdr.org/en_3892.svg"/>
</a>
```
when embedding without the fix, it links to a local/relative URL instead of tosdr.org wich usually just gives a 404

### How To Reproduce It
1. _Go to any service page_
3. _Scroll down to the privacy shield embed_
4. _See error_

### Expected behavior

The <a> element's href sould not be relative, but absolute and linkting to tosdr.org

**Comment by JustinBack** [comment]
Linked Jira Issue: https://tosdr.atlassian.net/browse/CRISP-189

**Comment by JustinBack** [comment]
Implemented Fix into Production, might take a while to appear there
