### ISSUE TITLE
Queries Isolate other ratings

### ISSUE THREAD

**Issue by DrKJeff16** [tosdr/CrispCMS#50]
When looking for a Service on the frontpage, and then deleting said query from the search bar, the ratings for the firstly displayed services are no longer available until either searching for another service, or refreshing.

**Comment by JustinBack** [comment]
The cause is the empty query catch uses the old Phoenix System

https://github.com/tosdr/CrispCMS/blob/3fa81355f665cee83e07cd01b406b5c1853c67ad/api/search.php#L13
