### ISSUE TITLE
embed service does not create a proper link if their service is not graded yet

### ISSUE THREAD

**Issue by pederdm000** [tosdr/CrispCMS#59]
embed service does not create a proper link if their service is not graded yet. For example the URL  will end with service /en_ one example of this is https://tosdr.org/en/service/2455. I assume that this is for any service that has no documents added yet but that would just be my guess.

**Comment by JustinBack** [comment]
That is weird considering they all use the same system. I'll debug this

**Comment by JustinBack** [comment]
The issue is in the Phoenix System by not creating a slug.

The service you mentioned has been created recently and does not have a slug yet
