### ISSUE TITLE
Update old Microsoft Edge logo

### ISSUE THREAD

**Issue by thatrobotdev** [tosdr/CrispCMS#60]
I noticed that https://tosdr.org/en/downloads has an old Microsoft Edge logo. I wanted to submit a PR, but I couldn't find the associated file in this repo (edge.svg), but I could find it in the archived website repo: https://github.com/tosdr/tosdr.org/blob/master/src/img/browser-extensions/icons/edge.svg.

<img width="811" alt="Screenshot of TOS;DR downloads page, in the microsoft edge section" src="https://user-images.githubusercontent.com/18013689/104825130-1c763b00-5815-11eb-9197-535d9ee7d589.png">

I couldn't find a press kit at https://www.microsoft.com/edge, but the new logo is featured prominently on the site.
<img width="219" alt="New Microsoft Edge logo" src="https://user-images.githubusercontent.com/18013689/104827017-ca361980-5816-11eb-94f0-5060326a3be3.png">

Hopefully this is helpful!

**Comment by JustinBack** [comment]
The Browser Extensions lie in the core plugin 

https://github.com/PixelcatProductions/CrispCMS-Plugin-Core/tree/c68462879d95cbfdca4fded452a0ae08dfab013e/img/browser-extensions/icons

(https://github.com/PixelcatProductions/CrispCMS-Plugin-Core/blob/c68462879d95cbfdca4fded452a0ae08dfab013e/img/browser-extensions/icons/edge.svg)

Will update the logo accordingly

**Comment by JustinBack** [comment]
It will take up to 24 hours to update properly

**Comment by thatrobotdev** [comment]
Awesome, thanks! 😁
