### ISSUE TITLE
Extra slash '/' at the end of service URL redirects to frontpage.

### ISSUE THREAD

**Issue by DrKJeff16** [tosdr/CrispCMS#63]
## Describe the bug
Adding a final to service pages (only those) redirects to frontpage.

## To Reproduce
1. Go to any service on ToS;DR (`tosdr.org/service/####`)
2. Add an extra slash at the end of the URL (`tosdr.org/service/####/`)
3. Enter.
4. You will get redirected to frontpage.

## Expected behavior
The redirection is not replicable on any other page within Crisp, regardless of language and/or session.
It only redirects on Service pages specifically, which could -though improbable, possible- cause confusion to users.

## Screenshots
![image](https://user-images.githubusercontent.com/72052712/107313207-b10c3b80-6a57-11eb-99a7-a5da6aec56f7.png)

![image](https://user-images.githubusercontent.com/72052712/107313273-cbdeb000-6a57-11eb-84e4-e1cd1ee0273a.png)
> Then press enter

![image](https://user-images.githubusercontent.com/72052712/107313328-e7e25180-6a57-11eb-94b8-e380838f7898.png)
> After press.

**Comment by JustinBack** [comment]
I think this is an issue in the route processing with the GET parameter where `q` does not get assigned due to the trailing slash

https://github.com/tosdr/CrispCMS/blob/e026b82e5c918530c0b21ec69a087835be5ed4b9/pixelcatproductions/class/crisp/api/Helper.php#L195-L220

**Comment by JustinBack** [comment]
Moved to jira
https://tosdr.atlassian.net/browse/CRISP-1
