### ISSUE TITLE
Website, along with the browser extention stopped working [Error 500]

### ISSUE THREAD

**Issue by Leakbang** [tosdr/CrispCMS#65]
Also this error shows up on the website `exception_cc927051-488a-b46e-ae11-e980619e8d77`
The browser extension also does not work. It does rate the websites but the pop-up never loads.
![image](https://user-images.githubusercontent.com/51197897/108624674-a59d1500-7446-11eb-82a2-8f970e1c3673.png)

**Comment by JustinBack** [comment]
Fixed in #66
