### ISSUE TITLE
Error on service page, service not found, on any service

### ISSUE THREAD

**Issue by augusto-herrmann** [tosdr/CrispCMS#72]
## Description
The service page, which should display all points of a given service, is no longer working.

### How To Reproduce It

1. Click on any service on the main page (e.g. Facebook).  You get an error:

> No matching services
No matching service has been found. You can add a service on our forum.<br><a class="btn btn-primary" href="https://forum.tosdr.org/request">Request a service</a> 

### Expected behavior
View the service grade and points.

### Screenshots
Screenshot for the Facebook service, but all get the same error.

![error-no-matching-services](https://user-images.githubusercontent.com/1058414/112045930-2c1e4280-8b2a-11eb-97e7-44e6ebf8b552.gif)

### Response Headers

```
HTTP/2 404 
server: nginx/1.19.8
date: Mon, 22 Mar 2021 19:21:48 GMT
content-type: text/html; charset=UTF-8
x-cluster: v2202103127645147153
set-cookie: PHPSESSID=********; path=/
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
set-cookie: crisp_universe=1; expires=Wed, 21-Apr-2021 19:21:48 GMT; Max-Age=2592000; path=/
set-cookie: crisp_language=en; expires=Wed, 21-Apr-2021 19:21:48 GMT; Max-Age=2592000; path=/
set-cookie: crisp_theme_mode=0; expires=Wed, 21-Apr-2021 19:21:48 GMT; Max-Age=2592000; path=/
x-cms-currentpage: 182
x-cms-locale: en
x-cms-universe: 1
x-cms-universe-human: UNIVERSE_PUBLIC
x-ratelimit-amount: 14
x-ratelimit-exceeded: false
x-ratelimit-limit: 15
x-ratelimit-interval: 1
x-ratelimit-indicator: 177.41.102.143
x-ratelimit-benefit: guest
x-cms-cdn: 
x-cms-shields: https://shields.tosdr.org
x-cms-api: https://api.tosdr.org
```

## Desktop Specs
 - OS: Ubuntu 20.04.1
 - Browser Firefox
 - Browser Version 86.0

**Comment by JustinBack** [comment]
This is interesting, I cannot reproduce this.

Can you give me links where this error occurs?


https://tosdr.org/en/service/190 for example works for me

**Comment by JustinBack** [comment]
curl -I https://tosdr.org/en/service/182
```
HTTP/2 200
server: nginx/1.19.8
date: Mon, 22 Mar 2021 19:45:12 GMT
content-type: text/html; charset=UTF-8
x-cluster: v2202103127645147153
set-cookie: PHPSESSID=8rg6b7iubaecvvjp7h5dmjmha9; path=/
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
set-cookie: crisp_universe=1; expires=Wed, 21-Apr-2021 19:45:12 GMT; Max-Age=2592000; path=/
set-cookie: crisp_language=en; expires=Wed, 21-Apr-2021 19:45:12 GMT; Max-Age=2592000; path=/
set-cookie: crisp_theme_mode=0; expires=Wed, 21-Apr-2021 19:45:12 GMT; Max-Age=2592000; path=/
x-cms-currentpage: service
x-cms-locale: en
x-cms-universe: 1
x-cms-universe-human: UNIVERSE_PUBLIC
x-ratelimit-amount: 12
x-ratelimit-exceeded: false
x-ratelimit-limit: 15
x-ratelimit-interval: 1
x-ratelimit-indicator: 202.61.251.191
x-ratelimit-benefit: guest
x-cms-cdn:
x-cms-shields: https://shields.tosdr.org
x-cms-api: https://api.tosdr.org
x-cms-logictime: 0.13011002540588
```

**Comment by augusto-herrmann** [comment]
It seems to be fixed now. :slightly_smiling_face: 

This morning, **every** service was giving a 404, including the one in your example above. I hope the problem doesn't come back.

**Comment by JustinBack** [comment]
Oh yes, a few hours ago I had to make changes to the routing process, causing the 404 for a couple minutes only.

**Comment by augusto-herrmann** [comment]
It seems the problem is back, but now on another URL. The press kit link is broken.

```
$ curl -I https://tosdr.org/en/presskit?download
HTTP/2 404 
server: nginx/1.19.8
date: Tue, 23 Mar 2021 03:19:44 GMT
content-type: text/html; charset=UTF-8
x-cluster: v2202103127645147153
set-cookie: PHPSESSID=******; path=/
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
set-cookie: crisp_universe=1; expires=Thu, 22-Apr-2021 03:19:44 GMT; Max-Age=2592000; path=/
set-cookie: crisp_language=en; expires=Thu, 22-Apr-2021 03:19:44 GMT; Max-Age=2592000; path=/
set-cookie: crisp_theme_mode=0; expires=Thu, 22-Apr-2021 03:19:44 GMT; Max-Age=2592000; path=/
x-cms-currentpage: presskit?download
x-cms-locale: en
x-cms-universe: 1
x-cms-universe-human: UNIVERSE_PUBLIC
x-ratelimit-amount: 14
x-ratelimit-exceeded: false
x-ratelimit-limit: 15
x-ratelimit-interval: 1
x-ratelimit-indicator: 177.41.102.143
x-ratelimit-benefit: guest
x-cms-cdn: https://cdn.tosdr.org
x-cms-shields: https://shields.tosdr.org
x-cms-api: https://api.tosdr.org
```

**Comment by JustinBack** [comment]
Interesting. The issue lies in the routing process since I switched it to a custom one.

https://github.com/tosdr/CrispCMS/blob/72aaa2a9ce311ed2c3cb417e45ab63889c16c7b8/themes/crisp/templates/views/presskit.twig#L37

I'll fix it

**Comment by augusto-herrmann** [comment]
> I'll fix it

Did you? I'm still getting the same error here.

**Comment by JustinBack** [comment]
it takes a while due to caching, up to a couple hours.

**Comment by augusto-herrmann** [comment]
It's been a few hours now. The problem persists. I guess we've got to wait more...

**Comment by JustinBack** [comment]
Yep its still cached ^^

![](https://i.imgur.com/90sKyNB.png)

**Comment by JustinBack** [comment]
Seems to be working fine now

**Comment by augusto-herrmann** [comment]
Yes, it's working. I finally managed to download the press kit. :slightly_smiling_face:

**Comment by JustinBack** [comment]
Great! (The presskit is stored on this repo as well! https://github.com/tosdr/CrispCMS/blob/master/themes/crisp/presskit/ToSDR.zip?raw=true)

**Comment by augusto-herrmann** [comment]
Oh! I hadn't noticed that. :see_no_evil:
