### ISSUE TITLE
http://tosdr.org/#soundcloud redirects me to https://service/soundcloud

### ISSUE THREAD

**Issue by saper** [tosdr/CrispCMS#74]
## Description

The browser gets redirected to /service/soundcloud when clicking on a "Soundcloud" link on https://tosback.org/

### How To Reproduce It

- visit https://tosback.org/
- ignore certificate expired warning if any (https://github.com/tosdr/tosback2/issues/77)
- click on a soundcloud link (or any other service)

### Observed behavior

- We fetch http://tosback.org/
- We got redirected to https://tosback.org/
- Somehow after a while the browser gets redirected to  https://service/soundcloud

### Expected behavior

- a requested service info should be shown

## Desktop Specs
- OS: FreeBSD
- Firefox/86.0
- Chrome/88.0.4324.182

**Comment by saper** [comment]
The code in question:

https://github.com/tosdr/CrispCMS/blob/ac67d9ea84aab928e907f63c8f05d519f1018016/themes/crisp/templates/views/frontpage.twig#L127-L131

seems to produce the following:

````
>> exp
(11) […]
​0: ""
​1: "https:"
​2: "https"
​3: "//tosdr.org"
​4: "tosdr.org"
​5: "/"
​6: undefined
​7: undefined
​8: "#soundcloud"
​9: "soundcloud"
​10: ""
​length: 11
​<prototype>: Array []
````

>> "/" + firstPortion + "/service/" + encodeURIComponent(window.location.hash.substr(1))
"//service/soundcloud"

**Comment by JustinBack** [comment]
Thanks for reporting this, it seems to have used the old system so I've gone ahead and fixed it.


It will take a couple hours to appear in production

**Comment by JustinBack** [comment]
See 07b9ff2e4c5d7eabf563a52a35d451de15e4a0e4
