### ISSUE TITLE
MOBY Group logo

### ISSUE THREAD

**Issue by Aayan811** [tosdr/CrispCMS#75]
Please make sure that the icon you're providing is a PNG and has a size of **72x72**. However, SVGs are preferred!

Icon:

![Moby_Group_Logo](https://user-images.githubusercontent.com/81914871/113688366-0fb60480-96eb-11eb-8a92-3d28ab3c90b1.png)

Please copy the URL for the Service on our database. You may look for it [here](https://edit.tosdr.org/services).

https://edit.tosdr.org/services/2983

**Comment by JustinBack** [comment]
The logo has been added.
