### ISSUE TITLE
Among Us logo

### ISSUE THREAD

**Issue by Aayan811** [tosdr/CrispCMS#77]
Icon:
![Among Us logo](https://user-images.githubusercontent.com/81914871/115544786-d5409000-a2c4-11eb-93f4-2d198b486b63.png)

https://edit.tosdr.org/services/2995

**Comment by JustinBack** [comment]
The logo has been added

![](https://images.s3.edge.jbcdn.net/uploads/2021/04/21/firefox_Pq4KU9pCHc.png)
